[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "pip install -e openbb_forecast",
]

[start]
cmd = "python app/workspace_server.py"
